package org.gavin101.priv.gbloods;

import org.powbot.api.Area;
import org.powbot.api.Tile;
import org.powbot.api.rt4.Player;
import org.powbot.api.rt4.Players;

import java.util.ArrayList;

public class Constants {

    public Constants() {
        super();
    }

    public ArrayList<String> userTaskList = new ArrayList<String>();

    public Player p() {
        return Players.local();
    }

    // Script vars
    public static final Area DENSE_RUNESTONE_AREA = new Area(new Tile(1759, 3859, 0), new Tile(1763, 3845, 0));
    public static final Area DARK_ALTAR_AREA = new Area(new Tile(1717, 3878, 0), new Tile(1719, 3883, 0));
    public static final Area BLOOD_ALTAR_AREA = new Area(new Tile(1716, 3831, 0), new Tile(1723, 3823, 0));
    public static final int BLOOD_RUNE_ID = 565;
    public static final int IDLE_MOVEMENT_ANIM = 808;

    // Actually the tile south of the shortcut tile. Idk why the walker wont move to the closest tile
    public static final Tile SHORTCUT_TILE = new Tile(1761, 3871, 0);
    public static final Tile OVER_SHORTCUT_TILE = new Tile(1761, 3874, 0);

    // Generated by Scripts.Util/GetWorlds.py
    public static final int[] WORLD_LIST = {
            303, 304, 305, 306, 307, 309, 310, 311, 312, 313, 314, 315, 317, 320,
            322, 323, 324, 325, 327, 328, 329, 330, 331, 332, 333, 334, 336, 337,
            339, 340, 341, 342, 343, 344, 346, 347, 348, 350, 351, 352, 354, 355,
            357, 358, 359, 360, 362, 367, 368, 369, 370, 374, 375, 376, 377, 378,
            387, 388, 389, 395, 421, 422, 424, 443, 444, 445, 446, 463, 464, 465,
            477, 478, 480, 481, 482, 484, 485, 486, 487, 488, 489, 490, 491, 492,
            494, 495, 496, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515,
            517, 518, 519, 520, 521, 522, 523, 524, 525, 531, 532, 534, 535, 542,
            544, };

}
